<<<<<<< HEAD
<<<<<<< HEAD
# Generated by Django 6.0.5 on 2026-05-27 07:52

import django.db.models.deletion
=======
# Generated by Django 6.0.2 on 2026-02-19 10:45

import django.db.models.deletion
from django.conf import settings
>>>>>>> origin/feature/backend-chat
=======
# Generated by Django 6.0.2 on 2026-05-31 00:40

import django.db.models.deletion
>>>>>>> origin/feature/backend-users
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
<<<<<<< HEAD
=======
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
>>>>>>> origin/feature/backend-chat
=======
>>>>>>> origin/feature/backend-users
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
<<<<<<< HEAD
=======
>>>>>>> origin/feature/backend-users
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_url', models.URLField()),
                ('file_type', models.CharField(max_length=50)),
<<<<<<< HEAD
=======
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('gif', 'GIF')], default='text', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('message', 'Zpráva'), ('friend_request', 'Žádost'), ('group_invite', 'Pozvánka')], max_length=50)),
                ('content', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
>>>>>>> origin/feature/backend-users
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('private', 'Soukromý'), ('group', 'Skupinový')], max_length=20)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.URLField(blank=True, null=True)),
<<<<<<< HEAD
                ('last_activity', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
=======
>>>>>>> origin/feature/backend-chat
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
<<<<<<< HEAD
                ('is_read', models.BooleanField(default=False)),
            ],
=======
                ('description', models.TextField(blank=True, null=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['type'], name='chat_chat_type_ee7fe0_idx'), models.Index(fields=['last_activity'], name='chat_chat_last_ac_2aa3f0_idx')],
            },
>>>>>>> origin/feature/backend-users
        ),
        migrations.CreateModel(
            name='ChatMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Vlastník'), ('admin', 'Správce'), ('member', 'Člen')], default='member', max_length=20)),
<<<<<<< HEAD
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='chat.chat')),
=======
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
>>>>>>> origin/feature/backend-chat
=======
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='chat.chat')),
>>>>>>> origin/feature/backend-users
            ],
        ),
    ]
