# Generated by Django 6.0.2 on 2026-06-02 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='is_resolved',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
